# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
gradle.cache.push=false

# Fabric Properties
# check these on https://fabricmc.net/develop
java_version=21
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.16.14

# Mod Properties
mod_version=1.2.0
maven_group=xen42.peacefulprogression
archives_base_name=peaceful-progression

# Dependencies
fabric_version=0.129.0

# Others
# https://www.curseforge.com/minecraft/mc-mods/jade/files/all
jade_version=19.3.2
# https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items
rei_version=20.0.810
# for REI - https://www.curseforge.com/minecraft/mc-mods/architectury-api
architectury_version=17.0.8
# for REI - https://www.curseforge.com/minecraft/mc-mods/cloth-config
cloth_config_version=19.0.147

# What recipe viewer to use by default ('rei', or 'none'. if you change it, don't push it)
recipe_viewer=none

# Publishing
modrinth_id=s09pWwK0
curseforge_id=1265958