# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
gradle.cache.push=false

# Fabric Properties
# check these on https://fabricmc.net/develop
java_version=21
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.10

# Mod Properties
mod_version=1.2.0
maven_group=xen42.peacefulprogression
archives_base_name=peaceful-progression

# Dependencies
fabric_version=0.118.0

# Others
# https://www.curseforge.com/minecraft/mc-mods/jade/files/all
jade_version=17.2.2
# https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items
rei_version=18.0.804
# for REI - https://www.curseforge.com/minecraft/mc-mods/architectury-api
architectury_version=15.0.3
# for REI - https://www.curseforge.com/minecraft/mc-mods/cloth-config
cloth_config_version=17.0.144

# What recipe viewer to use by default ('rei', or 'none'. if you change it, don't push it)
recipe_viewer=none

# Publishing
modrinth_id=s09pWwK0
curseforge_id=1265958
